### PR TITLE
fix: remove `mysql_secure_installation` from PostgreSQL

### PR DESCRIPTION
**Pull request by cschug**
What a blasphemy ;)

### CODE REVIEW

**Comment by landaal-ict** [comment]
Why remove mysql_secure_installation ?

**Comment by cschug** [comment]
@landaal-ict Not sure if you're trolling, but `mysql_secure_installation` is part of a MySQL installation which has nothing to do with PosgreSQL which this cheat sheet is about.

**Comment by landaal-ict** [comment]
It was a joke.. ;)

**Comment by ChristianLempa** [comment]
Please don't use the issues and PRs for jokes. Let's try to keep it as professional as we can, and focus on the task. I have created a discord channel for all contributors, where we can have a more off-topic discussion and I'd like you to invite to it 😊, but it's not the right place here.

**Pull request merged**
