### PR TITLE
Convert some backlinks to markdown style, add initial descriptions for empty notes

### PR DESCRIPTION
**Pull request by doctorfree**
Hi and thanks for the excellent work and for sharing it. 

This pull request includes the following changes:

- Add notes for `flatpak` and `network`
- Use markdown rather than wiki style backlinks in some notes
- Initial descriptions for some empty notes

Perhaps there is a reason you use Wiki style backlinks. I prefer Markdown style for readability and brevity. Either appear to work identically so I guess it's a matter of taste. There are still many Wiki style backlinks, not all were converted yet.

### CODE REVIEW

**Comment by doctorfree** [comment]
**[UPDATE]** I was wrong, markdown style backlinks work just like wiki style backlinks. Sorry for the confusion. It appears that there are 3 good ways to implement backlinks (that I am currently aware of):

- As you have done it with `FooBar ([[foobar]])`
- As this pull request did it with `[FooBar](foobar)`
- Using an alias where needed like `[[foobar|FooBar]]`

I am revising my markdown to use the wiki style backlinks with aliases where needed.

If you would like to incorporate my changes I will submit a new pull request.

re:

It looks like Obsidian does not recognize markdown style backlinks. Perhaps this is a configuration option, I am still looking into this. That is, when I change links like `foobar ([[foobar]])` to `[foobar](foobar)` Obsidian no longer thinks that is a backlink in the "Open backlinks" linked view.

Several of the changes in this pull request are exactly that - changing wiki style backlinks to markdown style backlinks. If Obsidian does not support that in its view of backlinks then it may not be desirable even though, in my opinion, it is preferable.

I'll investigate further.

**Comment by ChristianLempa** [comment]
Thanks for the contribution :) I think we need to go with the `**Foobar ([[foobar]])**` as it's the only useful way to ensure Obsidian uses correct backlinks, but still in another Markdown viewer it's comfortable to read and use.
Can you revert these changes please? I'd like to merge it afterward :)

**Comment by doctorfree** [comment]
I will revise internal links for broadest Markdown viewer coverage and resubmit a pull request. One of the problems with Markdown is that so many variants have risen, some supporting nifty features like Github flavor markdown etc. It is not immediately clear to the average author whether some feature of Markdown is standard or an enhancement of the flavor in use. For example, are link aliases like `[[mylink|My Link Document]]` standard in Markdown? I don't think aliases are part of any standard but they are supported almost everywhere. The most basic inline link style that has been part of Markdown since its initial release is `[My Link Document](mylink)`. This is what I would recommend for maximum portability. However, I think all of the afore mentioned link styles are supported by almost every viewer and platform.

I think the real problem with inline links to local documents is not the link syntax but the link location. Obsidian and nb both seem to be able to locate a relative link without needing to specify the path. That is, if a relative link is in the Obsidian vault or nb notebook then the path to the link document seems to be automatically generated. For example, in several documents in the `apps` folder there are inline relative links to `[[kubernetes]]` but the `kubernetes.md` document is located, relative to `apps/`, in `../kubernetes/kubernetes.md`. Obsidian and nb have no problem finding these types of local links but other markdown viewers may not. If portability across viewers is desired then don't these links need to include the path to the document?

I am not a Markdown viewer expert. I do not know how all of the various viewers would behave. I'm happy if my markdown works well on Github and Gitlab and that's pretty much the extent of my concern. But I would like for a repository such as these cheat sheets to be as portable as possible. I think using relative inline links of the form `[Foo Bar](../foo/bar)` is the most portable. What do you think?

**Comment by doctorfree** [comment]
I'm closing this pull request and will submit a new one for the `awk` command with extensive cheat sheet improvements and links the way I think is most portable. You can review that, tell me ok or no, do it this other way and I will adopt whatever style you prefer.

In this way we can establish a preferred link syntax prior to wholesale changes throughout. Also, I like `awk`.

**Pull request closed without merging**
