### PR TITLE
Adding cloud computing overview

### PR DESCRIPTION
**Pull request by puneet2715**
Please review and let me know if any changes are required to be made

### CODE REVIEW

**Review by reula001 — APPROVED** [review]
Correct typo fix

**Review by reula001 — APPROVED** [review]
Correct typo fix

**Comment by puneet2715** [comment]
Well apart from the typo, I added a small part of my notes just to get some feedback on the changes required from my side,if any

**Comment by thedatabaseme** [comment]
@puneet2715 Are those images you've attached created by yourself or did you copy / download them somewhere?

Apart from that, I've changed the subject of this PR in order to reflect the additions you really made.

**Comment by puneet2715** [comment]
Yes, those images are screenshots from a free training course by juniper networks - JNCIA-CLOUD, if the images need to be removed, please do let me know

**Comment by thedatabaseme** [comment]
> Yes, those images are screenshots from a free training course by juniper networks - JNCIA-CLOUD, if the images need to be removed, please do let me know

I'm not sure if we are allowed to copy content out of a training course, even if it is free to watch, we reuse the published stuff of someone else and make it updateable by everyone. Did you also copy content as text from the course? Can you share the link to this training here? I assume, we have to check under which "licence" this course has been published. But as said, I don't know for sure and would need to check.

@ChristianLempa what do you think on this?

**Comment by puneet2715** [comment]
link to the course - https://learningportal.juniper.net/juniper/user_activity_info.aspx?id=EDU-JUN-WBT-JOL-JNCIA-CLOUD

**Comment by thedatabaseme** [comment]
> link to the course - https://learningportal.juniper.net/juniper/user_activity_info.aspx?id=EDU-JUN-WBT-JOL-JNCIA-CLOUD

As far as I understand, this course is free when you have an active subscription (which costs money) on that learning platform. So I would say this is not safe to add this to this repo. Also I assume, that you've copied some of the information (text) out from this course?
Me for myself, I will decline this PR. But let me say, that I really feel sorry for the effort you obviously put into this update.

Kind regards
Philip

**Comment by puneet2715** [comment]
Yes, some text is also from the course but its manually typed, anyways, removing the images and changing the text would get the pr merged right ???

**Comment by ChristianLempa** [comment]
I agree with @thedatabaseme, there are two problems I see with this PR. First is, we can't add copy content from other sources. Second is, I'm uncertain how useful the content is without the images and further explanation. However, I like the idea to have something about cloud computing in the cheat-sheets.
Can you remove the images and also reduce it to one single document? I'd like to have something about "Economics", "Edge Computing", "Types of Cloud (public, private, hybrid)", and "Providers". The Providers would be perfect for backlinks to other pages and docs.
Please tell us, if you need assistance ;)

**Comment by puneet2715** [comment]
Images already deleted, I'll ask for help if I will require it.

**Comment by puneet2715** [comment]
Closing this pr and opening a new one with the requested changes

**Pull request closed without merging**
